on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        command:
          - go test .
          - go run .
    steps:
      - run: ${{ matrix.command }}
