on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        command:
          - go test .
          - go run .
    defaults:
      run:
        working-directory: ${{ startsWith(matrix.command, 'go') && 'go' || '.' }}
    steps:
      - uses: actions/checkout@v4
      - run: ${{ matrix.command }}
