on:
  push:
    branches:
      - main

jobs:
  go:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v4
      - run: go test .
      - run: go run .

  rust:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
      - run: cargo run

  python:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m unittest
      - run: python3 .
